name: flutter_onboard
description: A simple, elegant and easy to use onboard widget for both android and ios devices(Null-Safety).
version: 2.0.0
repository: https://github.com/Abdullahjavaid0331/ms-flutter-packages.git

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^1.1.0
  flutter_hooks: ^0.18.1
  hooks_riverpod: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.8.1
  freezed: ^1.1.0
  build_runner: ^2.1.7
flutter:
